id = "joisc-2012-sp-day4-2"
title = "joisc-2012-sp-day4-2"
url = "https://www2.ioi-jp.org/camp/2012/2012-sp-tasks/2012-sp-day4.pdf#2"

[limits]
tle_sec = 5.0
mle_mb = 512

[harness]
kind = "raw"

[testdata]
source = "manual"
name = "joisc-2012-sp-day4-2"

[compare]
kind = "tokens"
